insert into public.articles (
  id, source_url, source_name, category, published_at,
  title_nl, title_en, title_es, title_fa,
  summary_nl, summary_en, summary_es, summary_fa
) values
(
  'a8c1d2e3-4f56-4789-a012-b3c4d5e6f701',
  'https://www.omropfryslan.nl/nl/nieuws/17753351/voor-een-kamer-in-leeuwarden-moeten-studenten-dieper-in-de-buidel-tasten',
  'Omrop Fryslân',
  'politics',
  '2026-08-31T08:20:00+02:00',
  'Gemeente steunt honderd extra studentenwoningen bij NHL Stenden',
  'Council backs a hundred extra student rooms near NHL Stenden',
  'El ayuntamiento apoya cien habitaciones extra junto a NHL Stenden',
  'شورا با صد خوابگاه اضافه کنار ان‌اچ‌ال استندن موافقت کرد',
  'Het college wil tijdelijke units aan de Rengerslaan. Bewoners eisten eerst duidelijkheid over parkeren en geluid. Stemming volgt volgende week.',
  'The board wants temporary units on Rengerslaan. Neighbours asked first for a clear plan on parking and noise. The vote is next week.',
  'El gobierno local quiere módulos temporales en Rengerslaan. Los vecinos pidieron antes un plan claro de parking y ruido. La votación es la semana que viene.',
  'شهرداری واحدهای موقت در رنخرسلان می‌خواهد. همسایه‌ها اول طرح پارک و صدا خواستند. رأی‌گیری هفته بعد است.'
),
(
  'a8c1d2e3-4f56-4789-a012-b3c4d5e6f702',
  'https://www.lc.nl/regio/friesland/leeuwarden/aquaduct-tijdelijk-dicht-in-leeuwarden/157155527.html',
  'LC.nl',
  'infrastructure',
  '2026-08-30T16:40:00+02:00',
  'Wirdumerdijk twee weken dicht: bus 10 om via Zaailand',
  'Wirdumerdijk closed for two weeks: bus 10 reroutes via Zaailand',
  'Wirdumerdijk cerrado dos semanas: el bus 10 desvía por Zaailand',
  'ویردومردایک دو هفته بسته است: اتوبوس ۱۰ از زایلاند می‌رود',
  'Werk aan riolering start maandag 1 september. Fietsers kunnen door. Reken extra 8 minuten in de ochtendspits.',
  'Sewer works start Monday 1 September. Bikes can still pass. Add about 8 minutes in the morning rush.',
  'Las obras de alcantarillado empiezan el lunes 1 de septiembre. Las bicis pasan. Suma unos 8 minutos en la hora punta.',
  'کار فاضلاب دوشنبه ۱ سپتامبر شروع می‌شود. دوچرخه عبور می‌کند. صبح حدود ۸ دقیقه بیشتر حساب کنید.'
),
(
  'a8c1d2e3-4f56-4789-a012-b3c4d5e6f703',
  'https://omroepleeuwarden.nl/bruisende-markt-vol-kunst-muziek-dans-mienskip-en-lekker-eten-in-bouwurk-bij-de-oldehove/',
  'Omroep Leeuwarden',
  'culture',
  '2026-08-30T11:05:00+02:00',
  'Oldehove Night Markets: extra zaterdag in september',
  'Oldehove Night Markets: extra Saturday in September',
  'Oldehove Night Markets: sábado extra en septiembre',
  'بازار شب اولدهوفه: شنبه اضافه در سپتامبر',
  'Foodstalls en korte sets op het Oldehoofsterkerkhof. Toegang vrij. Laatste ronde 23:30 vanwege de buren.',
  'Food stalls and short sets on Oldehoofsterkerkhof. Free entry. Last round 23:30 for the neighbours.',
  'Puestos de comida y sets cortos en Oldehoofsterkerkhof. Entrada libre. Última ronda 23:30 por los vecinos.',
  'غذا و ست‌های کوتاه در اولدهوفسترکرک‌هوف. ورود آزاد. آخرین دور ۲۳:۳۰ به‌خاطر همسایه‌ها.'
),
(
  'a8c1d2e3-4f56-4789-a012-b3c4d5e6f704',
  'https://www.omropfryslan.nl/nl/nieuws/681024/de-meeste-fietsen-worden-gestolen-bij-station-leeuwarden',
  'Omrop Fryslân',
  'safety',
  '2026-08-29T18:15:00+02:00',
  'Politie: meer fietsdiefstallen rond station en Zaailand',
  'Police: more bike thefts around the station and Zaailand',
  'Policía: más robos de bici junto a la estación y Zaailand',
  'پلیس: دزدی دوچرخه اطراف ایستگاه و زایلاند بیشتر شده',
  'Vooral ’s avonds bij onverlichte rekken. Gebruik een tweede slot. Meld via 0900-8844, geen spoed.',
  'Mostly evenings at unlit racks. Use a second lock. Report on 0900-8844 if it is not urgent.',
  'Sobre todo por la noche en aparcamientos sin luz. Usa un segundo candado. Avisa al 0900-8844 si no es urgente.',
  'بیشتر شب‌ها کنار رک‌های بی‌نور. قفل دوم بزنید. اگر فوری نیست با ۰۹۰۰-۸۸۴۴ خبر دهید.'
),
(
  'a8c1d2e3-4f56-4789-a012-b3c4d5e6f705',
  'https://omroepleeuwarden.nl/leip-zo-ontdekken-eerstejaars-studenten-hun-nieuwe-stad/',
  'Omroep Leeuwarden',
  'education',
  '2026-08-29T09:30:00+02:00',
  'NHL Stenden opent semester: introweek tot donderdag',
  'NHL Stenden term opens: intro week runs through Thursday',
  'NHL Stenden abre el semestre: la intro sigue hasta el jueves',
  'ترم ان‌اچ‌ال استندن شروع شد: هفته آشنایی تا پنجشنبه',
  'Internationale studenten halen hun OV-chip en inschrijving bij het Student Service Centre. Avondprogramma in Neushoorn.',
  'International students pick up OV-chip cards and enrolment at the Student Service Centre. Evening programme at Neushoorn.',
  'Los estudiantes internacionales recogen el OV-chip y la matrícula en el Student Service Centre. Programa nocturno en Neushoorn.',
  'دانشجوهای بین‌المللی کارت او‌وی و ثبت‌نام را از مرکز خدمات دانشجویی می‌گیرند. برنامه شب در نویسهورن.'
),
(
  'a8c1d2e3-4f56-4789-a012-b3c4d5e6f706',
  'https://www.lc.nl/regio/friesland/leeuwarden/restaurant-de-gouverneur-opent-op-iconische-plek-in-het-centrum-van-leeuwarden-droom-komt-uit/156396143.html',
  'LC.nl',
  'business',
  '2026-08-28T13:50:00+02:00',
  'Drie nieuwe zaken openen in De Kelders deze maand',
  'Three new spots open on De Kelders this month',
  'Tres locales nuevos abren en De Kelders este mes',
  'این ماه سه جای جدید در ده کلدرز باز می‌شود',
  'Een lunchbar, een tweedehandsboekwinkel en een kleine wijnbar. Terrasplekken blijven beperkt tot de kade.',
  'A lunch counter, a second-hand bookshop and a small wine bar. Terrace seats stay limited to the quay.',
  'Un mostrador de comida, una librería de segundo uso y un vino pequeño. Las terrazas siguen solo en el muelle.',
  'یک ناهاربار، کتاب‌فروشی دست‌دوم و یک بار شراب کوچک. صندلی فضای باز فقط روی اسکله می‌ماند.'
),
(
  'a8c1d2e3-4f56-4789-a012-b3c4d5e6f707',
  'https://www.omropfryslan.nl/nl/nieuws/17862582/lees-terug-cambuur-koploper-na-zege-op-de-graafschap',
  'Omrop Fryslân',
  'sports',
  '2026-08-28T07:45:00+02:00',
  'Cambuur thuis tegen De Graafschap: poort open 18:00',
  'Cambuur at home vs De Graafschap: gates at 18:00',
  'Cambuur en casa contra De Graafschap: puertas a las 18:00',
  'کامبور در خانه برابر ده خراف‌اسخاپ: درها ساعت ۱۸:۰۰',
  'Klapstoelkaartjes nog via de club. Bus 2 rijdt extra ritten na afloop. Geen alcohol in de trein terug.',
  'Terrace tickets still via the club. Bus 2 adds extra runs after the match. No alcohol on the train back.',
  'Aún hay entradas de grada en el club. El bus 2 pone viajes extra al final. Sin alcohol en el tren de vuelta.',
  'بلیت جایگاه هنوز از باشگاه. اتوبوس ۲ بعد بازی اضافه می‌رود. در قطار برگشت الکل نیست.'
),
(
  'a8c1d2e3-4f56-4789-a012-b3c4d5e6f708',
  'https://omroepleeuwarden.nl/paddenschermen-beschermen-verliefde-padden-langs-fietspad-potmarge/',
  'Omroep Leeuwarden',
  'infrastructure',
  '2026-08-27T15:10:00+02:00',
  'Nieuw fietspad langs de Potmarge deels open',
  'New Potmarge bike path partly open',
  'El nuevo carril bici del Potmarge abre en parte',
  'مسیر دوچرخه جدید پوت‌مارخه نیمه‌باز شد',
  'Het stuk tot de Heliconweg is klaar. Het laatste deel naar het station volgt in oktober als het weer meezit.',
  'The stretch to Heliconweg is done. The last piece to the station follows in October if the weather holds.',
  'El tramo hasta Heliconweg ya está. El último tramo a la estación llega en octubre si el tiempo aguanta.',
  'قطعه تا هلی‌کن‌وخ تمام شد. تکه آخر تا ایستگاه اگر هوا بسازد اکتبر می‌آید.'
)
on conflict (id) do nothing;

insert into public.events (
  id, name, venue, event_datetime, genre, ticket_link, image_url,
  description_nl, description_en, description_es, description_fa
) values
(
  'b9d2e3f4-5a67-4890-b123-c4d5e6f70801',
  'Warehouse Frisian',
  'Neushoorn',
  '2026-09-05T23:00:00+02:00',
  'electronic',
  'https://neushoorn.nl/',
  null,
  'Twee zalen, techno en breaks. Deuren 23:00, last in 01:30. Geen gastlijst na middernacht.',
  'Two rooms, techno and breaks. Doors 23:00, last in 01:30. No guest list after midnight.',
  'Dos salas, techno y breaks. Puertas 23:00, último acceso 01:30. Sin lista después de medianoche.',
  'دو سالن، تکنو و بریکس. درها ۲۳:۰۰، ورود آخر ۰۱:۳۰. بعد نیمه‌شب لیست مهمان نیست.'
),
(
  'b9d2e3f4-5a67-4890-b123-c4d5e6f70802',
  'Intro Friday: International Mixer',
  'Neushoorn',
  '2026-09-04T21:30:00+02:00',
  'student-party',
  'https://neushoorn.nl/',
  null,
  'Eerstejaars en exchange. Gratis met studentenkaart tot 22:30. Jassen in de garderobe verplicht.',
  'First years and exchange students. Free with student card until 22:30. Coat check required.',
  'Primer curso e intercambio. Gratis con carnet hasta las 22:30. Guardarropa obligatorio.',
  'سال‌اولی و تبادل. تا ۲۲:۳۰ با کارت دانشجویی رایگان. سپردن کت لازم است.'
),
(
  'b9d2e3f4-5a67-4890-b123-c4d5e6f70803',
  'De Ossekop: local four-piece',
  'Café de Ossekop',
  '2026-09-05T20:00:00+02:00',
  'live-band',
  'https://www.ossekop.nl/',
  null,
  'Gitaar en NL/EN vocals. Staand, geen tickets vooraf. Begin stipt 20:30.',
  'Guitar and NL/EN vocals. Standing, no tickets in advance. Starts 20:30 sharp.',
  'Guitarra y voces NL/EN. De pie, sin entradas previas. Empieza a las 20:30 en punto.',
  'گیتار و آواز هلندی/انگلیسی. ایستاده، بلیت از قبل نیست. شروع دقیق ۲۰:۳۰.'
),
(
  'b9d2e3f4-5a67-4890-b123-c4d5e6f70804',
  'Late Cipher',
  'Club T',
  '2026-09-06T22:00:00+02:00',
  'hiphop',
  'https://www.instagram.com/',
  null,
  'Cypher open van 22:00 tot 23:00, daarna dj’s. 18+ en ID aan de deur.',
  'Open cypher 22:00 to 23:00, then DJs. 18+ and ID at the door.',
  'Cifrado abierto de 22:00 a 23:00, luego DJs. +18 y DNI en la puerta.',
  'سایفر باز از ۲۲:۰۰ تا ۲۳:۰۰، بعد دی‌جی. ۱۸+ و کارت شناسایی دم در.'
),
(
  'b9d2e3f4-5a67-4890-b123-c4d5e6f70805',
  'Domingo Latino',
  'De Koperen Tuin',
  '2026-09-06T16:00:00+02:00',
  'electronic',
  'https://www.dekoperentuin.nl/',
  null,
  'Salsa en cumbia in de middagzon. Gratis tot 19:00, daarna entreeprijs. Buiten als het droog blijft.',
  'Salsa and cumbia in the afternoon. Free until 19:00, then a door fee. Outside if it stays dry.',
  'Salsa y cumbia por la tarde. Gratis hasta las 19:00, luego entrada. Fuera si no llueve.',
  'سالسا و کومبیا بعدازظهر. تا ۱۹:۰۰ رایگان، بعد ورودی. اگر باران نباشد بیرون.'
),
(
  'b9d2e3f4-5a67-4890-b123-c4d5e6f70806',
  'Asteriks: residents + guest',
  'Podium Asteriks',
  '2026-09-04T22:30:00+02:00',
  'electronic',
  'https://www.instagram.com/',
  null,
  'Kleine zaal, house tot 03:00. Cap 120. Link in bio voor de gastlijst tot vrijdag 18:00.',
  'Small room, house until 03:00. Cap 120. Link in bio for the guest list until Friday 18:00.',
  'Sala pequeña, house hasta las 03:00. Cupo 120. Enlace en bio para la lista hasta el viernes 18:00.',
  'سالن کوچک، هاوس تا ۰۳:۰۰. ظرفیت ۱۲۰. لینک بیو برای لیست مهمان تا جمعه ۱۸:۰۰.'
)
on conflict (id) do nothing;
